### ISSUE TITLE
How to handle multilingual pages?

### ISSUE THREAD

**Issue by harmenjanssen** [grrr-amsterdam/nova-pages-tool#7]
Maybe we just... don't? Using the existing `language` column you can create pages in multiple languages. 
If you want to link to other pages in a language switcher, you would need to:

- Create a migration to add a foreign key to the pages table.
- Extend the Page resource and add fields to populate this foreign key.

This would become rather cumbersome when supporting more than two languages though, since that would need a many to many relationship.

**Comment by martijngastkemper** [comment]
And what happens with the page slug, we have to think about that. Adding the language to the URL is [recommended by Google](https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites). Or use different domains, but that makes the Cloudfront / S3 configuration much more complicated.

**Comment by harmenjanssen** [comment]
You can do that by making `nl` the slug of your homepage and adding all your Dutch pages as subpages of that page.
And do the same with a page with slug `en`. 
This will generate the recommended URL structure.
